### ISSUE TITLE
Ensure java 9 is supported

### ISSUE THREAD

**Issue by codingchili** [codingchili/chili-core#112]

**Comment by codingchili** [comment]
travis:

requires trusty: https://github.com/travis-ci/travis-ci/issues/7253

to enable oraclejdk9-switcher source:
https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/?utm_source=trusty-container-based-beta-notice&utm_medium=banner&utm_campaign=trusty-container-based-beta

**Comment by codingchili** [comment]
gradle 3.5 requires the following environment property to be set, as it hacks the classloader..
JDK_JAVA_OPTIONS='--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED'

source: 
https://github.com/gradle/gradle/issues/1095

**Comment by codingchili** [comment]
Builds failing, oracle.com 503 service unavailable

 sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install oracle-java9-installer
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  visualvm ttf-baekmuk ttf-unfonts ttf-unfonts-core ttf-kochi-gothic
  ttf-sazanami-gothic ttf-kochi-mincho ttf-sazanami-mincho ttf-arphic-uming
Recommended packages:
  oracle-java9-set-default
The following packages will be upgraded:
  oracle-java9-installer
1 upgraded, 0 newly installed, 0 to remove and 186 not upgraded.
Need to get 30.8 kB of archives.
After this operation, 21.5 kB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/webupd8team/java/ubuntu/ trusty/main oracle-java9-installer all 9b162-1~webupd8~0 [30.8 kB]
Fetched 30.8 kB in 0s (69.3 kB/s)
Preconfiguring packages ...
(Reading database ... 69904 files and directories currently installed.)
Preparing to unpack .../oracle-java9-installer_9b162-1~webupd8~0_all.deb ...
oracle-license-v1-1 license has already been accepted
Unpacking oracle-java9-installer (9b162-1~webupd8~0) over (9b140+9b140arm-1~webupd8~3) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for shared-mime-info (1.2-0ubuntu3) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Setting up oracle-java9-installer (9b162-1~webupd8~0) ...
No /var/cache/oracle-jdk9-installer/wgetrc file found.
Creating /var/cache/oracle-jdk9-installer/wgetrc and
using default oracle-java9-installer wgetrc settings for it.
Downloading Oracle Java 9...
--2017-05-19 05:04:12--  http://www.java.net/download/java/jdk9/archive/162/binaries/jdk-9-ea+162_linux-x64_bin.tar.gz
Resolving www.java.net (www.java.net)... 137.254.56.25
Connecting to www.java.net (www.java.net)|137.254.56.25|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://home.java.net/download/java/jdk9/archive/162/binaries/jdk-9-ea+162_linux-x64_bin.tar.gz [following]
--2017-05-19 05:04:12--  https://home.java.net/download/java/jdk9/archive/162/binaries/jdk-9-ea+162_linux-x64_bin.tar.gz
Resolving home.java.net (home.java.net)... 156.151.59.19
Connecting to home.java.net (home.java.net)|156.151.59.19|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.oracle.com/splash/java.net/maintenance/index.html [following]
--2017-05-19 05:04:13--  http://www.oracle.com/splash/java.net/maintenance/index.html
Resolving www.oracle.com (www.oracle.com)... 23.49.182.138, 2600:1408:10:184::2d3e, 2600:1408:10:185::2d3e
Connecting to www.oracle.com (www.oracle.com)|23.49.182.138|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2017-05-19 05:04:13 ERROR 503: Service Unavailable.
download failed
Oracle JDK 9 is NOT installed.
dpkg: error processing package oracle-java9-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java9-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
apt-get.diagnostics
apt-get install failed
$ cat ~/apt-get-update.log
Ign http://repo.mongodb.org trusty/mongodb-org/3.2 InRelease
Ign http://dl.google.com stable InRelease
Hit http://repo.mongodb.org trusty/mongodb-org/3.2 Release.gpg
Hit http://repo.mongodb.org trusty/mongodb-org/3.2 Release
Hit http://apt.postgresql.org trusty-pgdg InRelease
Hit http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse amd64 Packages
Ign http://toolbelt.heroku.com ./ InRelease
Hit http://dl.google.com stable Release.gpg
Hit http://dl.google.com stable Release
Hit http://apt.postgresql.org trusty-pgdg/main amd64 Packages
Hit http://toolbelt.heroku.com ./ Release.gpg
Hit http://dl.hhvm.com trusty InRelease
Hit http://toolbelt.heroku.com ./ Release
Hit http://dl.google.com stable/main amd64 Packages
Hit http://ppa.launchpad.net trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease
Hit http://dl.hhvm.com trusty/main amd64 Packages
Hit http://toolbelt.heroku.com ./ Packages
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty-updates InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty-security InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty-updates/main Sources
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty-updates/restricted Sources
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse Sources
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe Sources
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit https://packagecloud.io trusty InRelease
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit https://packagecloud.io trusty/main Sources
Hit http://archive.ubuntu.com trusty-security/main Sources
Hit http://archive.ubuntu.com trusty-security/restricted Sources
Hit https://packagecloud.io trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/multiverse Sources
Hit http://archive.ubuntu.com trusty-security/universe Sources
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
Hit http://archive.ubuntu.com trusty Release
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/multiverse Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Reading package lists...
Ign http://repo.mongodb.org trusty/mongodb-org/3.2 InRelease
Hit http://repo.mongodb.org trusty/mongodb-org/3.2 Release.gpg
Hit http://repo.mongodb.org trusty/mongodb-org/3.2 Release
Ign http://dl.google.com stable InRelease
Hit http://dl.hhvm.com trusty InRelease
Hit http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse amd64 Packages
Hit http://dl.google.com stable Release.gpg
Hit http://apt.postgresql.org trusty-pgdg InRelease
Hit http://dl.hhvm.com trusty/main amd64 Packages
Hit http://dl.google.com stable Release
Get:1 http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse i386 Packages [29 B]
Get:2 http://dl.hhvm.com trusty/main i386 Packages [20 B]
Hit http://dl.google.com stable/main amd64 Packages
Ign http://archive.ubuntu.com trusty InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://apt.postgresql.org trusty-pgdg/main amd64 Packages
Ign http://toolbelt.heroku.com ./ InRelease
Hit http://archive.ubuntu.com trusty-updates InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://toolbelt.heroku.com ./ Release.gpg
Hit http://toolbelt.heroku.com ./ Release
Get:3 http://apt.postgresql.org trusty-pgdg/main i386 Packages [118 kB]
Hit http://toolbelt.heroku.com ./ Packages
Hit http://archive.ubuntu.com trusty-security InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://ppa.launchpad.net trusty InRelease
Hit http://archive.ubuntu.com trusty-updates/main Sources
Hit http://archive.ubuntu.com trusty-updates/restricted Sources
Hit http://ppa.launchpad.net trusty InRelease
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse Sources
Get:4 http://ppa.launchpad.net trusty/main i386 Packages [1,611 B]
Hit http://archive.ubuntu.com trusty-updates/universe Sources
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Get:5 http://ppa.launchpad.net trusty/main i386 Packages [3,427 B]
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit https://packagecloud.io trusty InRelease
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Get:6 http://ppa.launchpad.net trusty/main i386 Packages [7,556 B]
Hit https://packagecloud.io trusty/main Sources
Get:7 http://archive.ubuntu.com trusty-updates/main i386 Packages [1,174 kB]
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Get:8 http://ppa.launchpad.net trusty/main i386 Packages [445 B]
Hit https://packagecloud.io trusty/main amd64 Packages
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Get:9 http://ppa.launchpad.net trusty/main i386 Packages [3,055 B]
Hit http://ppa.launchpad.net trusty/main amd64 Packages
Get:10 http://ppa.launchpad.net trusty/main i386 Packages [3,120 B]
Get:11 http://archive.ubuntu.com trusty-updates/restricted i386 Packages [20.9 kB]
Get:12 http://archive.ubuntu.com trusty-updates/multiverse i386 Packages [16.1 kB]
Get:13 http://archive.ubuntu.com trusty-updates/universe i386 Packages [526 kB]
Hit http://archive.ubuntu.com trusty-security/main Sources
Hit http://archive.ubuntu.com trusty-security/restricted Sources
Hit http://archive.ubuntu.com trusty-security/multiverse Sources
Hit http://archive.ubuntu.com trusty-security/universe Sources
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-security/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
Get:14 http://archive.ubuntu.com trusty-security/main i386 Packages [710 kB]
Get:15 http://archive.ubuntu.com trusty-security/restricted i386 Packages [17.5 kB]
Get:16 http://archive.ubuntu.com trusty-security/multiverse i386 Packages [4,186 B]
Get:17 http://archive.ubuntu.com trusty-security/universe i386 Packages [203 kB]
Hit http://archive.ubuntu.com trusty Release
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/multiverse Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Get:18 http://archive.ubuntu.com trusty/main i386 Packages [1,739 kB]
Get:19 http://archive.ubuntu.com trusty/restricted i386 Packages [16.4 kB]
Get:20 http://archive.ubuntu.com trusty/multiverse i386 Packages [172 kB]
Get:21 http://archive.ubuntu.com trusty/universe i386 Packages [7,597 kB]
Fetched 12.3 MB in 8s (1,503 kB/s)
Reading package lists...
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install oracle-java9-installer" failed and exited with 100 during .
Your build has been stopped.

**Comment by codingchili** [comment]
```
Resolving home.java.net (home.java.net)... 156.151.59.19
Connecting to home.java.net (home.java.net)|156.151.59.19|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.oracle.com/splash/java.net/maintenance/index.html [following]
--2017-05-19 05:11:08--  http://www.oracle.com/splash/java.net/maintenance/index.html
Resolving www.oracle.com (www.oracle.com)... 23.49.182.138, 2600:1408:10:185::2d3e, 2600:1408:10:184::2d3e
Connecting to www.oracle.com (www.oracle.com)|23.49.182.138|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2017-05-19 05:11:08 ERROR 503: Service Unavailable.
```

http://www.oracle.com/splash/java.net/maintenance/index.html ...

**Comment by codingchili** [comment]
Removed apt install for oraclejdk9-installer, jdk9 is already present on travis trusty dist.

**Comment by codingchili** [comment]
Updated travis configuration to use gradle wrapper rather than system default gradle version.

**Comment by codingchili** [comment]
Deployment tests are failing horribly

```
java.lang.IllegalStateException: failed to create a new resolver
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:83)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:711)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:74)
	at io.vertx.core.net.impl.NetServerBase.listen(NetServerBase.java:154)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:129)
	at io.vertx.core.net.impl.NetServerImpl.listen(NetServerImpl.java:124)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$start$1(ClusteredEventBus.java:146)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:188)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:287)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException: failed to create a new resolver
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:157)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67)
	... 16 more
Caused by: java.lang.NullPointerException
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:250)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:347)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.newNameResolver(DnsResolverProvider.java:153)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:84)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:73)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67)
	... 18 more
```

**Comment by codingchili** [comment]
`./gradlew build core:test`
returns 0 when tests are failing..

**Comment by codingchili** [comment]
Java 9 is ok.
